import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend, PieChart, Pie, Cell } from 'recharts';
import { LayoutGrid, Users, CreditCard, ArrowLeftRight, BarChart3, Search, RefreshCw, ArrowDownToLine, ArrowUpFromLine, CornerDownRight, CornerUpRight, CheckCircle2, Bell, ChevronRight, Wallet, Plus, Trash2, Edit3, X } from 'lucide-react';
import { api } from './services/api';

const NAV = [['dashboard','Dashboard',LayoutGrid],['accounts','Accounts',CreditCard],['transfer','Transfer',ArrowLeftRight],['customers','Customers',Users],['reports','Reports',BarChart3]];
const money = n => `₹${Math.abs(Number(n || 0)).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date = d => d ? new Date(d).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}) : '—';
const txMeta = { DEPOSIT:[ArrowDownToLine,'Deposit','var(--accent)'], WITHDRAW:[ArrowUpFromLine,'Withdraw','var(--danger)'], TRANSFER_IN:[CornerDownRight,'Transfer in','var(--mint)'], TRANSFER_OUT:[CornerUpRight,'Transfer out','var(--warn)'] };
function Logo(){ return <svg width="30" height="30" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="var(--elevated)" stroke="var(--border)"/><path d="M11 28V12h3.6l8.8 12.2V12H27v16h-3.6l-8.8-12.2V28H11Z" fill="var(--accent)"/><path d="m24 19 7-8m0 4v-4h-4" stroke="var(--mint)" strokeWidth="2" fill="none"/></svg> }
function Status({ok}){ return <span className="status-line"><span className={`status-dot ${ok?'ok':'bad'}`}/>{ok?'Oracle Database Connected':'Oracle Database Offline'}</span> }
function Stat({label,value,icon:Icon,sub='Live from Oracle'}){ return <div className="stat-card"><div className="stat-top"><span className="stat-icon"><Icon size={16}/></span><span className="stat-label">{label}</span></div><div className="stat-value">{value}</div><div className="stat-sub">{sub}</div></div> }
function Modal({title,children,onClose}){ return <div className="modal-backdrop"><div className="modal"><button className="close" onClick={onClose}><X size={16}/></button><h2>{title}</h2>{children}</div></div> }
function App(){
 const [active,setActive]=useState('dashboard'),[data,setData]=useState({customers:[],accounts:[],transactions:[],stats:{},analytics:[],reports:{}}),[health,setHealth]=useState({status:'unhealthy'}),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[lastSync,setLastSync]=useState(null),[error,setError]=useState(''),[modal,setModal]=useState(null),[search,setSearch]=useState('');
 const sync=useCallback(async()=>{setRefreshing(true);setError('');try{const [health,customers,accounts,transactions,stats,analytics,reports]=await Promise.all([api.health(),api.customers(),api.accounts(),api.transactions(),api.stats(),api.analytics(),api.reports()]);setHealth(health);setData({customers,accounts,transactions,stats,analytics,reports});setLastSync(new Date());}catch(e){setError(e.message);try{setHealth(await api.health())}catch{setHealth({status:'unhealthy'})}}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{sync();const timer=setInterval(sync,15000);return()=>clearInterval(timer)},[sync]);
 const filteredTx=useMemo(()=>data.transactions.filter(t=>!search||`${t.transaction_id} ${t.account_no} ${t.customer_name||''}`.toLowerCase().includes(search.toLowerCase())).slice(0,8),[data.transactions,search]);
 const mutate=async(account,action,amount)=>{try{await api.mutate(account,action,amount);setModal(null);await sync()}catch(e){setError(e.message)}};
 return <div className="nx-root"><aside className="sidebar"><div className="brand"><Logo/><div><b>NEXORA BANK</b><small>Banking, engineered for clarity.</small></div></div><nav>{NAV.map(([key,label,Icon])=><button key={key} className={active===key?'active':''} onClick={()=>setActive(key)}><Icon size={15}/>{label}</button>)}</nav><div className="sidebar-foot"><b>Demo Administrator</b><br/>Session · Oracle-backed</div></aside><main className="main"><header className="topbar"><label className="search-box"><Search size={14}/><input placeholder="Search customer, account, transaction ID" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="topbar-right"><Bell size={16}/><span className="avatar">DA</span></div></header><section className="content"><div className="hero"><div><h1>Good evening, Admin</h1><p>Your banking overview at a glance.</p></div><div className="sync-block"><Status ok={health.status==='healthy'}/><div className="sync-time">Last synchronized: <span>{lastSync?lastSync.toLocaleTimeString('en-IN'):'—'}</span></div><button className="refresh-btn" onClick={sync} disabled={refreshing}><RefreshCw size={13} className={refreshing?'spin':''}/>{refreshing?'Refreshing…':'Refresh data'}</button></div></div>{error&&<div className="error">{error}</div>}{active==='dashboard'&&<Dashboard data={data} loading={loading} tx={filteredTx} setModal={setModal} setActive={setActive}/>} {active==='accounts'&&<Accounts accounts={data.accounts} setModal={setModal} search={search}/>} {active==='customers'&&<Customers customers={data.customers} sync={sync} setModal={setModal}/>} {active==='transfer'&&<Transfer accounts={data.accounts} onDone={sync}/>} {active==='reports'&&<Reports data={data}/>}</section></main>{modal&&<ActionModal modal={modal} accounts={data.accounts} close={()=>setModal(null)} submit={mutate}/>}</div>
}
function Dashboard({data,loading,tx,setModal,setActive}){const s=data.stats||{}, a=data.analytics||[]; return <><div className="stat-grid"><Stat label="Total Customers" value={loading?'…':s.total_customers??0} icon={Users}/><Stat label="Total Accounts" value={loading?'…':s.total_accounts??0} icon={CreditCard}/><Stat label="Total Bank Balance" value={loading?'…':money(s.total_balance)} icon={Wallet}/><Stat label="Total Transactions" value={loading?'…':s.total_transactions??0} icon={ArrowLeftRight}/></div><div className="chart-grid"><Panel title="Balance Overview" sub="Current account balances from Oracle"><ResponsiveContainer width="100%" height={220}><AreaChart data={data.accounts}><CartesianGrid stroke="#243447" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="account_no" tick={{fill:'#9AA8B8',fontSize:11}}/><YAxis tick={{fill:'#9AA8B8',fontSize:11}} tickFormatter={v=>`₹${v/1000}k`}/><Tooltip formatter={v=>money(v)}/><Area type="monotone" dataKey="balance" name="Balance" stroke="#19C37D" fill="#19C37D" fillOpacity={.18}/></AreaChart></ResponsiveContainer></Panel><Panel title="Transaction Activity" sub="Aggregated from transaction records"><ResponsiveContainer width="100%" height={220}><BarChart data={a}><CartesianGrid stroke="#243447" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="label" tick={{fill:'#9AA8B8',fontSize:11}}/><YAxis tick={{fill:'#9AA8B8',fontSize:11}}/><Tooltip formatter={v=>money(v)}/><Legend/><Bar dataKey="deposits" fill="#19C37D"/><Bar dataKey="withdrawals" fill="#EF6262"/><Bar dataKey="transfers" fill="#8BE0BE"/></BarChart></ResponsiveContainer></Panel></div><TransactionTable tx={tx} onAll={()=>setActive('reports')}/></>}
function Panel({title,sub,children}){return <div className="panel"><div className="panel-head"><div><div className="panel-title">{title}</div><div className="panel-sub">{sub}</div></div></div>{children}</div>}
function TransactionTable({tx,onAll}){return <div className="panel-table"><div className="table-head"><div className="panel-title">Recent Transactions</div><button className="link" onClick={onAll}>View all <ChevronRight size={13}/></button></div><div className="table-scroll"><table><thead><tr><th>Type</th><th>Transaction ID</th><th>Customer</th><th>Account</th><th>Amount</th><th>Date</th><th>Status</th></tr></thead><tbody>{tx.length?tx.map(t=>{const [Icon,label,color]=txMeta[t.transaction_type]||txMeta.DEPOSIT;const positive=t.transaction_type==='DEPOSIT'||t.transaction_type==='TRANSFER_IN';return <tr key={t.transaction_id}><td><span className="tx-type"><span className="tx-type-icon"><Icon size={13} color={color}/></span>{label}</span></td><td className="mono">#{t.transaction_id}</td><td>{t.customer_name||'—'}</td><td className="mono">•••• {t.account_no}</td><td className={positive?'amt-pos':'amt-neg'}>{positive?'+':'−'}{money(t.amount)}</td><td className="muted">{date(t.transaction_date)}</td><td><span className="badge completed"><CheckCircle2 size={10}/>Completed</span></td></tr>}):<tr><td colSpan="7" className="empty">No transactions found</td></tr>}</tbody></table></div></div>}
function Accounts({accounts,setModal,search}){const rows=accounts.filter(a=>!search||`${a.account_no} ${a.customer_name} ${a.account_type}`.toLowerCase().includes(search.toLowerCase()));return <PageTitle title="Accounts" sub="Live account balances and actions"><div className="panel-table"><Table><thead><tr><th>Account Number</th><th>Customer</th><th>Type</th><th>Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(a=><tr key={a.account_no}><td className="mono">{a.account_no}</td><td>{a.customer_name}</td><td>{a.account_type}</td><td className="amt-pos">{money(a.balance)}</td><td><span className="badge completed">{a.status||'ACTIVE'}</span></td><td><button className="small-btn" onClick={()=>setModal({action:'deposit',account:a})}>Deposit</button> <button className="small-btn danger-btn" onClick={()=>setModal({action:'withdraw',account:a})}>Withdraw</button></td></tr>)}</tbody></Table></div></PageTitle>}
function Customers({customers,sync,setModal}){return <PageTitle title="Customers" sub="Customer records from CUSTOMER_ACCOUNT_VIEW" action={<button className="primary" onClick={()=>setModal({action:'customer'})}><Plus size={14}/>Add customer</button>}><div className="panel-table"><Table><thead><tr><th>ID</th><th>Name</th><th>Phone</th><th>Email</th><th>Accounts</th><th>Actions</th></tr></thead><tbody>{customers.map(c=><tr key={c.customer_id}><td>{c.customer_id}</td><td>{c.name}</td><td>{c.phone||'—'}</td><td>{c.email||'—'}</td><td>{c.account_count??0}</td><td><button className="icon-action" onClick={()=>setModal({action:'customer',customer:c})}><Edit3 size={14}/></button><button className="icon-action" onClick={async()=>{if(confirm('Delete this customer?')){try{await api.deleteCustomer(c.customer_id);sync()}catch(e){alert(e.message)}}}}><Trash2 size={14}/></button></td></tr>)}</tbody></Table></div></PageTitle>}
function Table({children}){return <div className="table-scroll"><table>{children}</table></div>}; function PageTitle({title,sub,action,children}){return <><div className="page-title"><div><h2>{title}</h2><p>{sub}</p></div>{action}</div>{children}</>}
function Transfer({accounts,onDone}){const [from,setFrom]=useState(''),[to,setTo]=useState(''),[amount,setAmount]=useState(''),[msg,setMsg]=useState('');const submit=async e=>{e.preventDefault();try{await api.transfer({from_account:Number(from),to_account:Number(to),amount:Number(amount)});setMsg('Transfer completed successfully');setAmount('');onDone()}catch(e){setMsg(e.message)}};const f=accounts.find(a=>String(a.account_no)===from),t=accounts.find(a=>String(a.account_no)===to);return <PageTitle title="Transfer" sub="Move funds through Oracle transfer_money"><form className="form-card" onSubmit={submit}><label>From account<select value={from} onChange={e=>setFrom(e.target.value)} required><option value="">Select source</option>{accounts.map(a=><option key={a.account_no} value={a.account_no}>{a.account_no} · {a.customer_name}</option>)}</select></label><label>To account<select value={to} onChange={e=>setTo(e.target.value)} required><option value="">Select destination</option>{accounts.map(a=><option key={a.account_no} value={a.account_no}>{a.account_no} · {a.customer_name}</option>)}</select></label><div className="preview"><span>Source balance <b>{money(f?.balance)}</b></span><span>Destination balance <b>{money(t?.balance)}</b></span></div><label>Transfer amount<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><button className="primary" type="submit">Confirm transfer</button>{msg&&<div className="success">{msg}</div>}</form></PageTitle>}
function Reports({data}){const s=data.stats||{},r=data.reports||{},a=data.analytics||[];return <PageTitle title="Reports" sub="Operational reporting calculated from Oracle"><div className="stat-grid"><Stat label="Total bank balance" value={money(s.total_balance)} icon={Wallet}/><Stat label="Deposits" value={money(r.total_deposits)} icon={ArrowDownToLine}/><Stat label="Withdrawals" value={money(r.total_withdrawals)} icon={ArrowUpFromLine}/><Stat label="Transfers" value={money(r.total_transfers)} icon={ArrowLeftRight}/></div><div className="chart-grid"><Panel title="Transaction type summary" sub="Aggregated amounts"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={a} dataKey="total" nameKey="label" outerRadius={90}>{a.map((_,i)=><Cell key={i} fill={['#19C37D','#EF6262','#8BE0BE'][i%3]}/>)}</Pie><Tooltip formatter={v=>money(v)}/><Legend/></PieChart></ResponsiveContainer></Panel><Panel title="Account type distribution" sub="Current Oracle accounts"><ResponsiveContainer width="100%" height={260}><BarChart data={data.accounts.reduce((r,a)=>{const x=r.find(v=>v.type===a.account_type);x?x.count++:r.push({type:a.account_type,count:1});return r},[])}><XAxis dataKey="type" tick={{fill:'#9AA8B8'}}/><YAxis tick={{fill:'#9AA8B8'}}/><Bar dataKey="count" fill="#19C37D"/></BarChart></ResponsiveContainer></Panel></div></PageTitle>}
function ActionModal({modal,accounts,close,submit}){const [amount,setAmount]=useState(''),[form,setForm]=useState(modal.customer||{});if(modal.action==='customer')return <Modal title={modal.customer?'Edit customer':'Add customer'} onClose={close}><form onSubmit={async e=>{e.preventDefault();try{modal.customer?await api.updateCustomer(modal.customer.customer_id,form):await api.createCustomer(form);close();location.reload()}catch(e){alert(e.message)}}}><input placeholder="Name" value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})} required/><input placeholder="Phone" value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="Email" type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/><button className="primary">Save customer</button></form></Modal>;const a=modal.account;return <Modal title={`${modal.action==='deposit'?'Deposit to':'Withdraw from'} ${a.account_no}`} onClose={close}><div className="account-summary"><b>{a.customer_name}</b><span>Current balance {money(a.balance)}</span></div><div className="quick">{[500,1000,2000,5000].map(n=><button key={n} onClick={()=>setAmount(n)}>₹{n.toLocaleString('en-IN')}</button>)}</div><input type="number" min="0.01" step="0.01" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="primary" onClick={()=>submit(a.account_no,modal.action,amount)}>Confirm {modal.action}</button></Modal>}
export default App;
